### PR TITLE
Adding Ratverse Ascension collection into registry

### PR DESCRIPTION
**Pull request by 0xyzid**
Adding Ratverse Ascension collection into registry

### CODE REVIEW

**Comment by ifavo** [comment]
@0xyzid looks mostly good, except can you check the tokenLink? Its goal is have link to each token on the entry, for example a deep link to a single token on World of V of BlackVeMarket. Right now it links to the example for VeChainStats

**Comment by 0xyzid** [comment]
Hi,

TokenLink updated with World of V link only.
Please check if it is correct.

**Comment by ifavo** [comment]
@0xyzid I believe `https://worldofv.art/token/0x1b60b8f4b83d146c051126873b9207247f7676ca/{{tokenId}}` would be the correct link for each token on WoV. The `{{tokenId}}` is replaced with the actual token id, like this: https://worldofv.art/token/0x1b60b8f4b83d146c051126873b9207247f7676ca/957


I believe the TestNet address is incorrect: https://explore-testnet.vechain.org/accounts/0x1b60b8f4b83d146c051126873b9207247f7676ca/

has no contract deployed on it, is that correct?

**Comment by 0xyzid** [comment]
sorry for the slow reply, I have updated the PR.

[image: image.png]

**Comment by ifavo** [comment]
> sorry for the slow reply, I have updated the PR.

the tokenLink is now hard coded and all tokens would link to 957 – can you make it dynamic like `https://worldofv.art/token/0x1b60b8f4b83d146c051126873b9207247f7676ca/{{tokenId}}` ?

**Comment by 0xyzid** [comment]
it has been updated.
[image: image.png]

**Comment by ifavo** [comment]
@0xyzid the checks failed, because the folder is not all lower case, can you make the address lower case?

`0x1b60b8f4b83d146c051126873b9207247f7676ca` 

… because you might encounter issues with your local filesystem, you might need to do this in two steps:

- rename to something totally different like: `_0x1b60b8f4b83d146c051126873b9207247f7676c`
- commit
- rename to `0x1b60b8f4b83d146c051126873b9207247f7676ca`
- commit

because some filesystems might not detect the case changes

**Comment by 0xyzid** [comment]
can you help me navigate the rename section, i think i cannot find how to
rename the folder

**Comment by 0xyzid** [comment]
[image: image.png]
i have updated the folder name. can you confirm if thi is correct?

**Comment by ifavo** [comment]
@0xyzid Sorry to have two more feedbacks:

-  the extra json has a `,` too much, which makes the json invalid
- Bildschirmfoto 2024-10-08 um 22 10 30

I believe you have a typo in your `info.json`:

```
    "name": "Ratverse Ascenion",
```

should it be `Ratverse Ascension` ?

**Comment by 0xyzid** [comment]
apologies on the error, i have updated as per feedback

**Comment by ifavo** [comment]
@libotony this looks good to me now, can you have another look?

**Comment by 0xyzid** [comment]
Apologies for the delay. All seems fine. Thanks for your help

**Comment by libotony** [comment]
Looks good to me!

**Review by libotony — APPROVED** [review]

**Pull request merged**
