### PR TITLE
Add veDelegate.vet

### PR DESCRIPTION
**Pull request by ifavo**
This PR adds the NFTs that have Token Bound Accounts linked to them, providing access to the staked tokens.

### CODE REVIEW

**Comment by ifavo** [comment]
@libotony would you be so kind to verify the new entry?

**Comment by libotony** [comment]
@ifavo Is there a place in the website mentioning it will have a NFT?

**Comment by ifavo** [comment]
> @ifavo Is there a place in the website mentioning it will have a NFT?

Not yet, the new site will be up later today and mention it. Its however not very prominent, to avoid confusion … VeWorld does automatically detect NFTs, showing the meta information is therefor very relevant.

**Review by libotony — APPROVED** [review]

**Comment by ifavo** [comment]
@libotony thank you 🙏

**Pull request merged**
