### PR TITLE
BRUSHIZER COLLECTION

### PR DESCRIPTION
**Pull request by Mezange**

### CODE REVIEW

**Comment by ifavo** [comment]
@Mezange looks good now!
@libotony can you have a second look?

**Comment by libotony** [comment]
@Mezange The website is not accessible https://www.brushizer.com/, could you check? Other part looks good to me

**Comment by Mezange** [comment]
I have been working on the website solo since 2021, are you interested in discovering the project?

**Comment by ifavo** [comment]
> I have been working on the website solo since 2021, are you interested in discovering the project?

I think a broken link is bad quality for the entry. The link should be online available when made public, publishing a broken link should be avoided.

**Comment by Mezange** [comment]
I am working on the creation of the website. I'm 70% of the way to making a light version.

I will get back to you as soon as possible to inform you of the website going online in order to validate the collection on the blockchain.

It's OK for you ?

**Comment by ifavo** [comment]
> I am working on the creation of the website. I'm 70% of the way to making a light version.
> 
> I will get back to you as soon as possible to inform you of the website going online in order to validate the collection on the blockchain.
> 
> It's OK for you ?

I think best would be to remove it until you have one. You can always add another PR to update the details, when its available. There is no benefit of users linking to an unavailable website.

**Comment by Mezange** [comment]
After months of solo work, the site is finally online ! 

I hope you enjoy the work ! :

I can't wait to organize NFT hunts in our cities ! 🥇 

https://brushizer.com

**Comment by libotony** [comment]
> After months of solo work, the site is finally online !
> 
> I hope you enjoy the work ! :
> 
> I can't wait to organize NFT hunts in our cities ! 🥇
> 
> https://brushizer.com

LGTM, @ifavo could you take another look?

**Review by libotony — APPROVED** [review]

**Pull request merged**
