### PR TITLE
$lion x Graphite Black Card

### PR DESCRIPTION
**Pull request by Harufriend**
$lion x Graphite Black Card Nft

### CODE REVIEW

**Comment by ifavo** [comment]
@Harufriend can you please adjust the image to 256x256px?

**Review by Harufriend — COMMENTED** [review]
change of token size, 256 x 256

**Comment by ifavo** [comment]
- search for contract address links to https://worldofv.art/collection/448a6e39-b211-40dd-8350-fa894ab852dd 

@libotony this looks good to me, what do you think?

**Comment by libotony** [comment]
> * search for contract address links to https://worldofv.art/collection/448a6e39-b211-40dd-8350-fa894ab852dd
> 
> @libotony this looks good to me, what do you think?

LGTM

**Review by libotony — APPROVED** [review]

**Pull request merged**
