### PR TITLE
BRUSHIZER COLLECTION

### PR DESCRIPTION
**Pull request by Mezange**

### CODE REVIEW

**Comment by ifavo** [comment]
@Mezange Can you please check the failed build?

It requires the contracts folder to be all lower case:

```
path: /home/runner/work/nft-registry/nft-registry/tokens/main/0xba2834c43670a28175F965Be544386D04B602243
message: "folder name should be a valid address with lower case"
```

Can you please adjust? :-)

**Comment by Mezange** [comment]
Hi my friend :) 

I don't know if the commit went through... can you put everything in lowercase for me if my commit didn't go through ?

Everything is good ?

**Comment by ifavo** [comment]
@Mezange it still contains upper case chars. Likely because you just renamed and comitted locally, I suggest to:

1. rename
2. commit
3. rename to lower case
4. commit again

Otherwise the case-insensitivity in some filesystems can mess this up sometimes. Or you just fork a again in a fresh repo and add the folder in lower case.

**Comment by Mezange** [comment]
I renamed the folder name but during commit it does not change.

What am I supposed to do? :/ lol

**Comment by ifavo** [comment]
> I renamed the folder name but during commit it does not change.
> 
> What am I supposed to do? :/ lol

Did you rename it to something different like `_x-something-else`, so it won't be the same folder at the end?

You can also create a new branch of fork a new repo, and add it in lower case again.

**Pull request closed without merging**
